template: classic
base: header
user: wangxu-dev

# 语言比例
plugin_languages: yes
plugin_languages_sections: most-used
plugin_languages_details: percentage
plugin_languages_limit: 8
plugin_languages_threshold: 2%

# 技术栈图标
plugin_topics: yes
plugin_topics_mode: icons
plugin_topics_limit: 20
